drop table voter_list;

create table voter_list (
	Last_Name		varchar(128),
	First_Name		varchar(128),
	Middle_Name		varchar(128),
	Suffix			varchar(128),
	Sex			varchar(128),
	Date_Of_Birth		date,
	Date_Registered		date,
	Voter_Status		varchar(128),
	StatusChangeDate	date,
	Political_Party		varchar(128),
	House			varchar(128),
	HouseNoSuffix		varchar(128),
	StreetNameComplete	varchar(128),
	Apt			varchar(128),
	Address_Line_2		varchar(128),
	City			varchar(128),
	State			varchar(128),
	Zip_Code		varchar(128),
	MapAddress		varchar(512),
	MAddress_Line_1		varchar(128),
	MAddress_Line_2		varchar(128),
	MCity			varchar(128),
	MState			varchar(128),
	MZip_Code		varchar(128),
	PollingPlaceDescript	varchar(128),
	PollPlaceAdd		varchar(128),
	PollPlaceCSZ		varchar(128),
	Region			varchar(16),
	Last_Date_Voted		date,
	Precinct		varchar(128),
	Ward			varchar(128),
	School			varchar(128),
	Municipality		varchar(128),
	Magisterial		varchar(128),
	Legislative		varchar(128),
	Senatorial		varchar(128),
	Congressional		varchar(128),
	County			varchar(128),
	Rep_State_Comm		varchar(128),
	Dem_Zone		varchar(128),
	Rep_Zone		varchar(128),
	Precinct_Split		varchar(128),
	Date_Last_Changed	date,
	PhoneNumHome		varchar(128),
	PRIMARY KEY ( Last_Name, First_Name, Date_Of_Birth)
);
